### PR TITLE
cleaning code

### PR DESCRIPTION
**Pull request by Tr0nYx**
- removed tabs from modules/admin2/amind2rest.php & metadata.php
- removed unused params from function getData in Rest_Client
- changed commenting style in Product.php function init()

### CODE REVIEW

**Comment by jkrug** [comment]
Hi,
thank you for your work.
Could you explain, what was your intention to remove the parameters?
What's the ideo of reformatting comments?

**Comment by Tr0nYx** [comment]
Those Params are not really used imho and its ~ 1ms faster
Phpcheckstyle gives warnings for this commenting style, but normally its exactly the same. So the only, real small, advantage is better readability.

**Comment by jkrug** [comment]
These params are NOT YET used. Maybe we should have a short chat about the scruture and the ideas that lay behind the code. 

For the comments: This could be configured in PhpCheckStyle. Thats something we should discuss for sure and should publish. It's just a matter of agreement from all included developers.

Would love to get in touch with you to discuss and go on with you.

**Comment by Tr0nYx** [comment]
ah so some1 forgot to comment it out :)
if you want u can add me @skype: steve_kn ;)

**Pull request merged**
